### ISSUE TITLE
Menu display suggestion 

### ISSUE THREAD

**Issue by Gubbledenut** [bazmonk/digigurdy-baz#36]
Have one line along the top with the tuning showing in format C Cc C only as in trompette low hi chanter drone 
If one or the other is muted , it can be designated "0" So it would read 0 Cc C if the trompette is muted
Could include the Midi pitch ie C3 C3c4 C2 
Will try to see it transpose and capo stay will fit eg.
T-12 C3 C4c5 C2 C+1
The rest of the display can be used to show note being played ,either text or txt and bitmap???
I will do some testing on the code this weekend, to see how things fit

**Comment by bazmonk** [comment]
> Will try to see it transpose and capo stay will fit eg.
> T-12 C3 C4c5 C2 C+1

With sharps and flats in the mix it won't.  The size 1 font gives you 21-character lines exactly.

We've got more horizontal space to work with.  A third display option could be "Big note on left + compact readout on the right".

**Comment by bazmonk** [comment]
Didn't mean to close this :-)

**Comment by Gubbledenut** [comment]
it's unlikely you will have sharps and flats in tunings..if it's a transpose then live with it, but playing in minor key will still only have full notes tuning
it's another argument to just have the common sharps and flats listed and used for the keys we play in, rather than everything, sure add an option for everything, but for mostly G/C and D/G tunes, and for a learning point perspective, I think it's more sense to use below rather than everything???
So ;
Db is not used as much as C#
D# is not used as much as Eb
Gb is not used as much as F#
A# is not used as much as Bb
Ab is not used as much as G#

**Comment by bazmonk** [comment]
Let's see what becomes possible with variable-width fonts.  They're skinnier :-)
`Let's see what becomes possible with variable-width fonts.  They're skinnier :-)`

u8g2 should buy us a little more room.  I'm not super-looking forward to re-doing the notes and staff.  I did some crazy array stuff to align all those stupid bitmaps ;-)

But, maybe a third play screen option (or fourth I guess), that's completely re-imagined with proper spacing of nice fonts and more status info and I can just print the note names in a large font instead of generating bitmaps ever again.

**Comment by Gubbledenut** [comment]
ok love the new fonts and setup in the u8g2 test
I like the idea of a rotary push knob, but as John suggests perhaps for most of the venues repurpose the +/- buttons as up/down in menus with A as enter...then out of menus while playing the +/- go back to being transpose ones? 
I can easily put in a rotary/push thing...but as we would still have the  pushbuttons for capo, Transpose +/- and crank ..plus the three Ex ones..may as well utilise them more fully?
